### ISSUE TITLE
No ReadMe or documentation?

### ISSUE THREAD

**Issue by steve6375** [a1ive/diskfire#2]
Pls add some doc on what this is and usage, etc.
when you get time...

**Comment by a1ive** [comment]
This project is not yet finished and current features may be removed in the future.

**Comment by steve6375** [comment]
OK - someone pointed the project out to me so I assumed it was an 'announced' project from somewhere.

**Comment by a1ive** [comment]
Actually, this project is an experiment to port the grub2 filesystem driver to Windows to facilitate development and testing.
